// Reads blogs/*.md (optional YAML frontmatter: title, date, tags) and writes
// src/data/blogs.generated.js for the virtual filesystem. Runs via the
// prestart/prebuild/pretest npm hooks; see the blog feature spec in docs/.

const fs = require('fs');
const path = require('path');

const BLOGS_DIR = path.join(__dirname, '..', 'blogs');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'data', 'blogs.generated.js');

function parseFrontmatter(text) {
  const empty = () => ({ title: null, date: null, tags: [] });
  text = text.replace(/\r\n?/g, '\n');
  const lines = text.split('\n');
  if (lines[0] !== '---') {
    return { meta: empty(), body: text };
  }
  let closing = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === '---') {
      closing = i;
      break;
    }
  }
  if (closing === -1) {
    // Unclosed block: treat the whole file as body, no metadata.
    return { meta: empty(), body: text };
  }
  const meta = empty();
  for (const line of lines.slice(1, closing)) {
    const match = line.match(/^(title|date|tags):\s*(.*)$/);
    if (!match) continue;
    const key = match[1];
    const value = match[2].trim();
    if (key === 'tags') {
      meta.tags = value
        .replace(/^\[/, '')
        .replace(/\]$/, '')
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean);
    } else {
      meta[key] = value;
    }
  }
  const body = lines.slice(closing + 1).join('\n').replace(/^\n+/, '');
  return { meta, body };
}

function sortPosts(posts) {
  return [...posts].sort((a, b) => {
    if (a.date && b.date) {
      if (a.date !== b.date) return a.date < b.date ? 1 : -1;
      return a.slug.localeCompare(b.slug);
    }
    if (a.date) return -1;
    if (b.date) return 1;
    return a.slug.localeCompare(b.slug);
  });
}

function loadBlogs(dir) {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter((name) => name.endsWith('.md'));
  const posts = files.map((fileName) => {
    const slug = fileName.replace(/\.md$/, '');
    const raw = fs.readFileSync(path.join(dir, fileName), 'utf8');
    const { meta, body } = parseFrontmatter(raw);
    return {
      slug,
      title: meta.title || slug,
      date: meta.date,
      tags: meta.tags,
      content: body,
    };
  });
  return sortPosts(posts);
}

function main() {
  const posts = loadBlogs(BLOGS_DIR);
  const output =
    '// AUTO-GENERATED by scripts/generate-blogs.js — do not edit by hand.\n' +
    `export const blogs = ${JSON.stringify(posts, null, 2)};\n`;
  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`generate-blogs: wrote ${posts.length} post(s) to src/data/blogs.generated.js`);
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error(`generate-blogs failed: ${err.message}`);
    process.exit(1);
  }
}

module.exports = { parseFrontmatter, sortPosts, loadBlogs };
